apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-landingpage
  labels:
    app: nginx-landingpage
spec:
  selector:
    matchLabels:
      app: nginx-landingpage
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-landingpage
    spec:
      containers:
      - name: nginx-landingpage
        image: aditiaipr/landingpage:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landingpage-service
spec:
  selector:
    app: nginx-landingpage
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
